---
on:
  push:
    branches:
      - test
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20
          cache: gradle

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebugOpt -x assembleRelease

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: app/build/distributions/debugOpt